"""Compatibility exports for the archived multiscale diagnostic."""

from opening_strength_fit.legacy.multiscale_bucket_diag import (
    CANONICAL_WEIGHTING,
    GROUP_COLS,
    LABEL_COLS,
    PREDICTION_COLS,
    MultiscaleBucketDiagConfig,
    add_bucket_summaries,
    add_ic_rows,
    build_shape_summary,
    fixed_score_spearman,
    load_label_for_year,
    next_label_path,
    normalize_date,
    prediction_path,
    process_shard,
    run_multiscale_bucket_diagnostics,
    stock_pool_membership_mask,
    summarize_ic,
    summarize_monthly_stability,
    summarize_variant_average,
    write_frame,
)

__all__ = [
    "CANONICAL_WEIGHTING",
    "GROUP_COLS",
    "LABEL_COLS",
    "PREDICTION_COLS",
    "MultiscaleBucketDiagConfig",
    "add_bucket_summaries",
    "add_ic_rows",
    "build_shape_summary",
    "fixed_score_spearman",
    "load_label_for_year",
    "next_label_path",
    "normalize_date",
    "prediction_path",
    "process_shard",
    "run_multiscale_bucket_diagnostics",
    "stock_pool_membership_mask",
    "summarize_ic",
    "summarize_monthly_stability",
    "summarize_variant_average",
    "write_frame",
]
